### ISSUE TITLE
Other conversions not reflected in the notebook

### ISSUE THREAD

**Issue by sayakpaul** [tulasiram58827/craft_tflite#2]
I don't see the other conversion recipes you took in the conversion notebook. Could you include them? 

You can also consider clearing the unnecessary outputs from the notebooks to keep them clean.

**Comment by tulasiram58827** [comment]
Will update and let you know.

**Comment by tulasiram58827** [comment]
@sayakpaul  Update colab notebook with all other conversation recipes. Will clean them shortly.

**Comment by tulasiram58827** [comment]
Done. Feel free to reopen if issue still exists.
