### ISSUE TITLE
run  with craft.onnx 

### ISSUE THREAD

**Issue by SabraHashemi** [tulasiram58827/craft_tflite#4]
Hi, 
thanks for this amazing work, 
i'm running craft in 111 ms  on windows, but i want to get maximum  speed up  , so i want to use onnx and i'm new to that,
but i'm confused that which scripts should i use to test? 
( i want to use craft.onnx model so i dont need to produce it ) 

in below code line it is .pth version of craft.
parser.add_argument('--trained_model', default='../models/craft_mlt_25k.pth', type=str, help='pretrained model')

**Comment by tulasiram58827** [comment]
Hey @sabrabano0  You can use this [Notebook](https://github.com/tulasiram58827/craft_tflite/blob/main/colabs/pytorch_to_onnx.ipynb) to convert and do inference with ONNX model. If you just want to do inference just use the last block of the [Notebook](https://github.com/tulasiram58827/craft_tflite/blob/main/colabs/pytorch_to_onnx.ipynb)

**Comment by SabraHashemi** [comment]
net.load_state_dict(copyStateDict(torch.load('craft_mlt_25k.pth', map_location='cpu')))

as above line you first load pth model and convert it to onnx after this line .  
also your code is using craft in cpu mode  that is so slow.


your didnt use pycuda and tensorrt to run onnx?  am i right?

**Comment by tulasiram58827** [comment]
@sabrabano0 ONNX is a unified model format. It doesn't matter whether I load the PyTorch model in CPU or GPU while converting to ONNX. If I am loading the PyTorch model in GPU then I need to use inputs in GPU similarly for CPU. If you need to use Tensorrt then you should convert ONNX model to Tensorrt again

**Comment by SabraHashemi** [comment]
thank you for reply, 
im new to onnx , 
i want a script that work on test image and get result with onnx model ,  in my search:  it needs tensorrt and on windows tensorrt didnt have any pythonAPI, so i cant use it 
but i want to know can i use onnx without tensorrt? dose it have good exe time for an image? 
i ran craft on cuda and my avg time is 111ms
i want better exe time

 block that you mention in first reply is not what i mean. :(output is bleow)

Model loaded
Time taken for Pytoch model 0:00:01.692594
Output size torch.Size([1, 112, 112, 2])
Model ran sucesfully
Model converted succesfully
Model checked succesfully
Time taken for Onnx model 0:00:00.261490


any suggestion is  appreciated
thank you.

**Comment by tulasiram58827** [comment]
I think you misunderstood about ONNX. For running the ONNX model you don't need Tensorrt.

To decrease the latency you can first try converting the ONNX model to Tensorrt and then you need to do inference with the Tensorrt model on Nvidia GPU(Tensorrt is only optimized for NVIDIA GPUs). I don't know the support of Tensorrt on Windows machine. You can try using Google colab if you want to do inference with Tensorrt easily

**Comment by SabraHashemi** [comment]
we can run onnx  models on  various ML frameworks , converting the models is not the important subject here, when you decide to use tensorrt you convert onnx to trt ,  i know about that, base subject is about  finding best framework  or  info about exe time of running this project!  
 i want to run it on tensorrt to get best performance, i asked about time you get by running this on your selected framework, in your code you imported tensorflow backend but didnt use that , i think your repo is incomplete or you didnt run craft and just converting models.

**Comment by tulasiram58827** [comment]
This repository aims to convert PyTorch pre-trained model to TFLite. I think you did not seen the Repository files completely. `CRAFT_TFLITE.ipynb` contains end to end code for conversion and inference of TFLite model. If you have any queries or issues running TFLite model please go through other issues as some queries are already addressed. Regarding timing of the model please go through the README as it is already mentioned. Please go through the README and complete project and let me know still if you need any help.

This repository does not address conversion to Tensorrt.
